name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: utahkt/amazoniap-test

    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Start up tomcat
      run: /usr/local/tomcat/bin/startup.sh
    - name: Run Tests
      run: mix test
